name: Discord
version: 0.0.1
main: creeperplayer20\discord\Main
api: 4.2.0
src-namespace-prefix: creeperplayer20\discord

commands:
    discord:
        description: "§o§7Sends a §bdiscord§f§7 invite link"
        usage: "/discord"
        aliases: [dc]
        permission: "discord.use"
permissions:
    discord.use:
        default: true
