name: c20s-discord
version: 0.0.1
main: creeperplayer20\discord\Main
api: 4.0.8
src-namespace-prefix: creeperplayer20\discord

commands:
    discord:
        description: "Sends a §bdiscord§f invite link"
        usage: "/discord"
        permission: "discord.command"
permissions:
    discord.command:
        default: true
